### ISSUE TITLE
iOS Crash with Capacitor live mode

### ISSUE THREAD

**Issue by kristojorg** [newrelic/newrelic-capacitor-plugin#102] opened 2024-09-05 15:00 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

I am seeing crashes in iOS when trying to run the app specifically using capacitor's live development mode with this plugin.

The crash is this error:
```
let headersDict = NewRelic.generateDistributedTracingHeaders()
^ Thread 3: EXC_BAD_ACCESS (code=1, address=0x0)
```
in the file `NewRelicCapacitorPluginPlugin.swift:599`.

## Steps to Reproduce

1. Install newrelic plugin 1.5 in a capacitor app with iOS.
2. Run `npx cap run -l --port 8100 --host localhost ios`
3. See the above crash

## Expected Behavior

No crash 

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

- iOS 17.2
- iPhone 15 Pro
- Macbook Pro M1
- Capacitor 6
- Node 20
- Xcode 15.4
- Mac OS Sonoma 14.5

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

When running the app with a static web bundle, it does not crash.

[TIP]:  # ( Add any other context about the problem here. )

**Comment by ndesai-newrelic** [comment] 2024-09-06 19:30
@kristojorg can you provide sample app? we are unable to reproduce this issue.

**Comment by ndesai-newrelic** [comment] 2024-09-16 22:44
@kristojorg it is fixed now. can you test it now?

**Closed by ndesai-newrelic** 2024-09-16 22:44 UTC
Labels: bug

**Comment by kristojorg** [comment] 2024-09-20 10:11
Unfortunately we were experiencing too many crashes in production and have stopped using new relic for the time being. Thanks for fixing though!

**Comment by ndesai-newrelic** [comment] 2024-09-20 15:16
@kristojorg can you share crash reports so we can fix that for Future releases?
